### ISSUE TITLE
polling -> infinity_polling

### ISSUE THREAD

**Issue by Badiboy** [otter18/telegram-bot-template#2]
To avoid bot death on any exception you should better use infinity_polling instead of polling... Even in test environment.

**Comment by Badiboy** [comment]
Also it seems more gentle to use

`temp = request.get_data().decode('utf-8')`

instead of

`temp = request.stream.read().decode("utf-8")`

**Comment by otter18** [comment]
`request.stream.read().decode("utf-8")` is taken from [official examples](https://github.com/eternnoir/pyTelegramBotAPI/blob/87bce0bce149bc6b3aa67f1252a3115273d94c3f/examples/webhook_examples/webhook_flask_heroku_echo.py#L24)

**Comment by otter18** [comment]
fixed by 19d08e574844f0b981141978140dc61d2c58aa75

**Comment by Badiboy** [comment]
> request.stream.read().decode("utf-8") is taken from official example

Example was commited by one of the users.

stackoverflow recommends get_data:
https://stackoverflow.com/questions/10999990/get-raw-post-body-in-python-flask-regardless-of-content-type-header

Please, try with get_data (I have no possibility to test on heroku):
```
@server.route('/' + TOKEN, methods=['POST'])
def getMessage():
#    bot.process_new_updates([telebot.types.Update.de_json(request.stream.read().decode("utf-8"))])
    json_string = request.get_data().decode('utf-8')
    update = telebot.types.Update.de_json(json_string)
    bot.process_new_updates([update])
    return "!", 200
```
If it's fine - I'll update the example.

**Comment by otter18** [comment]
I've tested it for you at 763e8ff6ba26f4d1ddb3463269420de6158abcd9.
Apparently, for this particular example it work exactly the same.
```python
@app.route('/' + WEBHOOK_TOKEN, methods=['POST'])
def getMessage():
    # temp = request.stream.read().decode("utf-8")
    temp = request.get_data().decode("utf-8")
    temp = telebot.types.Update.de_json(temp)
    logger.debug('New message received. raw: %s', temp)
    bot.process_new_updates([temp])
    return "!", 200
```

**Comment by Badiboy** [comment]
Thanks, example updated. :)
